name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint
        run: test -z "$(gofmt -l .)"

      - name: Build
        run: go build -v ./cmd/...

      - name: Test
        run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Check coverage
        run: bash <(curl -s https://codecov.io/bash)
